Clang-tidy and include-what-you-use warnings
gazebosim/gz-utils pull request #107
Opened 2023-09-21 13:36 UTC by mjcarroll

2023-09-29 16:43 UTC, ahcorde requested changes

2023-09-29 16:43 UTC, ahcorde commented on test/integration/implptr/implptr_test_classes.hh
>        /// \brief Set the int value held by the pimpl
include `\param _value` here and below

2023-10-04 15:04 UTC, mjcarroll commented on test/integration/implptr/implptr_test_classes.hh
>        /// \brief Set the int value held by the pimpl
Done.

2023-10-04 15:56 UTC, ahcorde approved these changes

2023-10-04 17:02 UTC, iche033 commented on test/integration/implptr/implptr_test_classes.hh
> +      public: [[nodicard]] const std::string &GetString() const;
```suggestion
      public: [[nodiscard]] const std::string &GetString() const;
```

2023-10-12 22:14 UTC, azeey commented
DCO is failing

2023-10-13 14:39 UTC, merged