ign -> gz Migrate Ignition headers
gazebosim/gz-utils pull request #84
Opened 2022-12-01 18:40 UTC by nkoenig

See: https://github.com/gazebo-tooling/release-tools/issues/784

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-12-01 18:54 UTC, scpeters reviewed
do you mind squashing the last 3 commits? It's easier to review if the first commit just renames the headers and then a second commit modifies things

2022-12-01 18:54 UTC, scpeters commented on include/ignition/utils/config.hh
> +#define IGNITION_GUI__CONFIG_HH_
replace `GUI` with `UTILS`

2022-12-01 21:20 UTC, nkoenig commented on include/ignition/utils/config.hh
> +#define IGNITION_GUI__CONFIG_HH_
[e1c99ab](https://github.com/gazebosim/gz-utils/pull/84/commits/e1c99ab5d67d2c6b04ca43c1b117399892ba8489)

2022-12-01 21:21 UTC, nkoenig commented
> do you mind squashing the last 3 commits? It's easier to review if the first commit just renames the headers and then a second commit modifies things

Done.

2022-12-01 21:51 UTC, scpeters commented on include/ignition/utils/config.hh
> +#define GZ_GUI__CONFIG_HH_
```suggestion
#ifndef IGNITION_UTILS__CONFIG_HH_
#define IGNITION_UTILS__CONFIG_HH_
```

2022-12-01 21:51 UTC, scpeters commented on include/gz/utils/NeverDestroyed.hh
> +///   static const igntion::utils::NeverDestroyed<Dict> string_to_enum
```suggestion
///   static const ignition::utils::NeverDestroyed<Dict> string_to_enum
```

2022-12-01 22:23 UTC, nkoenig commented on include/ignition/utils/config.hh
> +#define GZ_GUI__CONFIG_HH_
Done.

2022-12-01 22:23 UTC, nkoenig commented on include/gz/utils/NeverDestroyed.hh
> +///   static const igntion::utils::NeverDestroyed<Dict> string_to_enum
Done

2022-12-01 23:12 UTC, nkoenig commented
Should I also update the contents of the `cli` directory?

2022-12-02 17:56 UTC, scpeters commented
> Should I also update the contents of the `cli` directory?

yes, good point. I would follow the pattern on the [`gz-utils2` branch](https://github.com/gazebosim/gz-utils/tree/gz-utils2/cli/include)

2022-12-05 18:52 UTC, nkoenig commented
> > Should I also update the contents of the `cli` directory?
> 
> yes, good point. I would follow the pattern on the [`gz-utils2` branch](https://github.com/gazebosim/gz-utils/tree/gz-utils2/cli/include)

Great. I update the CLI directory in a few commits that should make it easy to review:

1. Moved ignition directories to gz: [01326df](https://github.com/gazebosim/gz-utils/pull/84/commits/01326dfbb099e34f56c024b1e946b3f32e4082e9)
2. Copied the ignition directories from gz-utils2: [9822a1a](https://github.com/gazebosim/gz-utils/pull/84/commits/9822a1a488f22caa28eafe6d684df3f1d525b984)
3. Renamed IgnitionFormatter.hpp: [b539c89](https://github.com/gazebosim/gz-utils/pull/84/commits/b539c896ddc26a3dba13a6d673632a25016b7630)
4. Updated CMake and gz naming in GzFormatter.hpp: [91e1cda](https://github.com/gazebosim/gz-utils/pull/84/commits/91e1cdac1b0d26af5ee76d054170ae65d9f14173)

2022-12-07 18:30 UTC, mjcarroll approved these changes

2022-12-07 18:58 UTC, scpeters requested changes
I have some small changes I'd like to make to whitespace and squashing commits and will push directly to this branch with my fixes later today

2022-12-08 18:56 UTC, scpeters approved these changes
I'm made some more changes and squashed putting all file renames in the first commit, most documentation changes in the last commit, and everything else in the middle commit

2022-12-08 21:49 UTC, merged